### ISSUE TITLE
rocker-compose ?

### ISSUE THREAD

**Issue by orensbruli** [osrf/rocker#214] opened 2023-03-17 19:03 UTC
I'm loving rocker!
I was wondering if someone found a way to launch several containers. I know rocker it's not a replacement for docker-compose, but like a wrapper around docker, but it would be great to have some kind of declarative way to use it to launch several images. Something like
`rocker compose rocker-compose.yaml`. The way a see it, the syntax of the file could be mostly the same as a docker-compose.yaml but with an entry for each image with the rocker-specific options.

**Comment by 130s** [comment] 2023-03-17 19:07
https://github.com/osrf/rocker/issues/148 can be related.

**Comment by tfoote** [comment] 2023-03-27 17:36
I'm going to close this as a duplicate of #148 Please follow up there relating to the feature request.

**Closed by tfoote** 2023-03-27 17:36 UTC
