### ISSUE TITLE
It's stopped docker pull on Ubuntu 24.04

### ISSUE THREAD

**Issue by NakanishiKM** [osrf/rocker#280] opened 2024-06-27 09:39 UTC
I conveniently using rocker everyday.

This time occur problems rocker command after host machine was upgraded Ubuntu 24.04.

1. The rocker command could not be executed in Ubuntu 24.04's default version Python 3.12.3, due to version issues of related packages.
    > rocker: error: DependencyMissing encountered: Docker Client failed to connect to docker daemon. Please verify that docker is installed and running. As well as that you have permission to access the docker daemon. This is usually by being a member of the docker group. The underlying error was:
"""
Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
"""

    Its problem can be solved, using pyenv(example python 3.10.x).
2. There is no stdout where step is image pull(example 'FROM golang:1.19 as detector') by rocker on pyenv.
    That time nothing some error log, and if there are image cash, proceed.

I don't know cause, but I shared to temporary workaround.

**Comment by tfoote** [comment] 2024-07-11 22:33
That sounds like the upgrade might not have upgraded rocker and you possibly have cached dependencies on the older version of python in possibly a pyc file, or your upgrade changed the default version of python but didn't install all the dependencies in the new version of python. 

How did you install rocker?

**Comment by NakanishiKM** [comment] 2024-07-12 01:00
Thank you for your reply.

In correctly I did clean install Ubuntu 24.04, so I think that there are no dependencies.
For the default python, I installed both apt and pip to check, and for pyenv I installed rocker by pip.

**Comment by tfoote** [comment] 2024-07-17 17:26
Can you provide instructions on how to reproduce this issue (including your installation process) as well as exactly what you did to resolve it? The error that you're showing doesn't indicate a version issue but a dependency issue.

**Comment by tfoote** [comment] 2024-07-22 15:26
I've just tested on a Ubuntu 24.04 machine with the default 3.12.3 machine. The error in the original report suggests that there was a permissions issue with access to the docker daemon. This is resolved by adding yourself the the group. However that does't take effect by default until you log out and back in. To that end the fact that this was fixed when a new env was setup which might have triggered a new console and group persmissions and is why the behavior changed. 

Since I can't reproduce this and the error looks like a different issue I'm going to close it out. If you can reproduce it please comment back and we can reopen this.

**Closed by tfoote** 2024-07-22 15:26 UTC

**Comment by SevenFo** [comment] 2024-09-09 06:03
I encountered the same error on Ubuntu 24.04 after installing `rocker` via `apt`.

Initially, I faced a `ModuleNotFoundError: No module named 'distutils'` error, which I resolved by installing `python3-setuptools`.

However, now I'm encountering this error when running `rocker --help`:

```
~$ rocker --help
usage: rocker [-h] [--noexecute] [--nocache] [--nocleanup] [--pull] [--version] [--cuda] [--dev-helpers]
              [--devices [DEVICES ...]] [--env NAME[=VALUE] [NAME[=VALUE] ...]] [--env-file ENV_FILE]
              [--expose EXPOSE] [--git] [--git-config-path GIT_CONFIG_PATH] [--group-add GROUP_ADD] [--home]
              [--hostname HOSTNAME] [--name NAME]
              image [command ...]
rocker: error: DependencyMissing encountered: Docker Client failed to connect to docker daemon. Please verify that docker is installed and running. As well as that you have permission to access the docker daemon. This is usually by being a member of the docker group. The underlying error was:
"""
Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
"""
```

Despite this, running `docker` (without `sudo`) works normally, and I have already added my user to the Docker group.

**Comment by tfoote** [comment] 2024-09-09 06:57
Please open a new issue with full reproductions of what you did to install rocker, (apt sources commands etc) and what versions you have installed of rocker and docker. When you installed distutils how did you install that? We need to have enough information to find out how to reproduce the issue to help you. And also how is docker installed, and can you confirm the version of the daemon and how it's being run on your system.
