### ISSUE TITLE
Install nvidia-docker 2 / Nvidia-toolkit on ubuntu 23.04

### ISSUE THREAD

**Issue by Mk-arc** [osrf/rocker#232] opened 2023-05-07 08:00 UTC
Title says it all. The packages seem to be not available. How to use rocker with nvidia on ubuntu 23.04?

**Comment by tfoote** [comment] 2023-05-12 12:43
Please elaborate what your issues is. Can you please provide enough information to reproduce your issue and explain exactly what's not working with rocker?

**Comment by Mk-arc** [comment] 2023-05-12 12:46
Hi, 

thanks for coming back to this. 

you state in the Readme to follow this link to install the necessary nvidia components:

```
Install nvidia-docker 2: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
```

However, this is not working with ubuntu 23.04. There are no official releases.

I guess the question is. Are there any workarounds / is there a plan to support newer ubuntu versions.

**Comment by tfoote** [comment] 2023-05-13 00:04
To use the nvidia plugins for rocker it does require the nvidia-docker capabilities on your host. That's a hard dependency for using nvidia inside of docker. You can likely use other GPUs and all the other features of rocker you just won't be able to take advantage of the nvidia features.

There's no known workarounds. We will try to support it when/if NVIDIA makes a release. I would suggest following up with a request to NVIDIA. However looking at their support chart it looks like they're targeting only Ubuntu LTS releases so the next one supported by NVIDIA may be 24.04.

**Comment by tfoote** [comment] 2023-05-17 22:57
I don't think that there's anything we can do for this until there's an upstream release and at that point it will hopefully just work. So I'm going to close this.

**Closed by tfoote** 2023-05-17 22:57 UTC
